TestJQuery/Models/CarDto.cs
using System;

namespace TestJQuery.Models
{
    public class CarDto
    {
        public int Id { get; set; }

        public string Manufacturer { get; set; }

        public string Model { get; set; }

        public double Engine { get; set; }

        public int Year { get; set; }

        public DateTime DeliveredOn { get; set; }
    }
}

TestJQuery/Models/CarViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace TestJQuery.Models
{
    public class CarViewModel
    {
        [Required]
        public int Id { get; set; }

        [Required]
        [MaxLength(50)]
        public string Manufacturer { get; set; }

        public IList<string> AvailableManufacturers { get; set; }

        [Required]
        [MaxLength(50)]
        public string Model { get; set; }

        [Required]
        [Range(0.2, 10.0)]
        public double Engine { get; set; }

        [Required]
        [Range(1900, 2200)]
        public int Year { get; set; }

        [DisplayName("Delivered")]
        public DateTime DeliveredOn { get; set; }
    }
}

TestJQuery/Controllers/CarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using TestJQuery.Filter;
using TestJQuery.Models;
using TestJQuery.Reposirtory;
using TestJQuery.Reposirtory.Models;

namespace TestJQuery.Controllers
{
    public class CarController : Controller
    {
        [HttpGet]
        public ActionResult LoadCars(int count, int skip)
        {
            var searchResult = GetCarsFromRepository(count, skip, null).ToArray();
            if (!searchResult.Any())
                return Json(new { Message = "No data." }, JsonRequestBehavior.AllowGet);
            return Json(searchResult.Select(c =>
                new CarDto
                {
                    Model = c.Model,
                    Manufacturer = c.Manufacturer,
                    Year = c.Year,
                    Engine = c.Engine,
                    Id = c.Id,
                    DeliveredOn = c.DeliveredOn
                }).ToList(), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult LoadCars(int count, int skip, CarFilter filter)
        {
            var searchResult = GetCarsFromRepository(count, skip, filter).ToArray();
            if (!searchResult.Any())
                return Json(new { Message = "No data." }, JsonRequestBehavior.AllowGet);
            return Json(searchResult.Select(c =>
                new CarDto
                {
                    Model = c.Model,
                    Manufacturer = c.Manufacturer,
                    Year = c.Year,
                    Engine = c.Engine,
                    Id = c.Id,
                    DeliveredOn = c.DeliveredOn
                }).ToList(), JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult GetOne(int id)
        {
            var car = new CarRepository().GetItem(id);
            if (car == null)
                return Json(new { Error = "Car was not found." });
            return Json(
                new CarDto
                {
                    Model = car.Model,
                    Manufacturer = car.Manufacturer,
                    Year = car.Year,
                    Engine = car.Engine,
                    Id = car.Id,
                    DeliveredOn = car.DeliveredOn
                }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult CarEditDialog(int? id)
        {
            CarViewModel viewModel;
            if (id.HasValue)
            {
                var car = (new CarRepository()).GetItem(id.Value);
                if (car == null)
                    return Json(new {Error = "Car was not found."});
                viewModel = new CarViewModel
                {
                    Model = car.Model,
                    Manufacturer = car.Manufacturer,
                    Year = car.Year,
                    Engine = car.Engine,
                    Id = car.Id,
                    DeliveredOn = car.DeliveredOn
                };
            }
            else
            {
                viewModel = new CarViewModel
                {
                    Id = 0,
                    Year = DateTime.Today.Year,
                    DeliveredOn = DateTime.Today
                };
            }
            var manufacturers = new List<string> { null };
            manufacturers.AddRange((new ManufacturerRepository()).GetList().OrderBy(i => i));
            viewModel.AvailableManufacturers = manufacturers;
            return View("CarEditDialog", viewModel);
        }

        [HttpPost]
        public ActionResult CarEditDialog(CarViewModel car)
        {
            if (car.Year > DateTime.Today.Year)
            {
                ModelState.AddModelError(nameof(car.Year), "Too large for me.");
                ModelState.AddModelError(nameof(car.Year), "Be careful.");
            }
            if (!ModelState.IsValid)
            {
                var keys = ModelState.Keys.Where(k => ModelState[k].Errors.Any());
                return Json(new
                {
                    Errors = keys.ToDictionary(k => k, k => ModelState[k].Errors.Select(e => e.ErrorMessage).ToList())
                });
            }

            //Add a new car.
            if (car.Id <= 0)
            {
                var isValidAdd = (new CarRepository()).AddCar(new CarModel
                {
                    Model = car.Model,
                    Manufacturer = car.Manufacturer,
                    Year = car.Year,
                    Engine = car.Engine,
                    Id = car.Id,
                    DeliveredOn = car.DeliveredOn
                });
                return isValidAdd > 0 ? Json("Valid!!!") : Json(new { Errors = new[] { "Something wrong" } });
            }

            //Add a new car.
            var isValidEdit = (new CarRepository()).EditCar(new CarModel
            {
                Model = car.Model,
                Manufacturer = car.Manufacturer,
                Year = car.Year,
                Engine = car.Engine,
                Id = car.Id,
                DeliveredOn = car.DeliveredOn
            });
            return isValidEdit ? Json("Valid!!!") : Json(new { Errors = "Car was not found." });
        }

        private IEnumerable<CarModel> GetCarsFromRepository(int count, int skip, CarFilter filter)
        {
            return new CarRepository().GetList(count, skip, filter);
        }
    }
}

TestJQuery/Controllers/ManufacturerController.cs
using System.Linq;
using System.Web.Mvc;
using TestJQuery.Reposirtory;

namespace TestJQuery.Controllers
{
    public class ManufacturerController : Controller
    {
        [HttpGet]
        public ActionResult LoadManufacturers()
        {
            return Json(new ManufacturerRepository().GetList().Select(m => m.Clone()).ToList(), JsonRequestBehavior.AllowGet);
        }
    }
}

TestJQuery/Views/Car/CarEditDialog.cshtml
@model TestJQuery.Models.CarViewModel

<link rel="stylesheet" type="text/css" href="../../Content/Custom/CarEditDialog.css">
<div>
    @using (Html.BeginForm("CarEditDialog", "Car", null, FormMethod.Post, new { id = "addEditCarForm" }))
    {
        @Html.HiddenFor(c => c.Id)
        <table id="addEditCarData">
            <tbody>
                <tr>
                    <td>@Html.LabelFor(c => c.Manufacturer)</td>
                    <td>
                        @Html.DropDownListFor(
                            c => c.Manufacturer,
                            new List<SelectListItem>(Model.AvailableManufacturers.Select(m => new SelectListItem {Text = m, Value = m})),
                            new { @class = "form-control" })
                    </td>
                </tr>
                <tr><td></td><td>@Html.ValidationMessageFor(c => c.Manufacturer)</td></tr>
                <tr class="row-separator"></tr>
                <tr>
                    <td>@Html.LabelFor(c => c.Model)</td>
                    <td>
                        @Html.EditorFor(c => c.Model, new { htmlAttributes = new { @class = "form-control" } })
                    </td>
                </tr>
                <tr><td></td><td>@Html.ValidationMessageFor(c => c.Model)</td></tr>
                <tr class="row-separator"></tr>
                <tr>
                    <td>@Html.LabelFor(c => c.Engine)</td>
                    <td>
                        @Html.EditorFor(c => c.Engine, new { htmlAttributes = new { @class = "form-control" } })
                    </td>
                </tr>
                <tr><td></td><td>@Html.ValidationMessageFor(c => c.Engine)</td></tr>
                <tr class="row-separator"></tr>
                <tr>
                    <td>@Html.LabelFor(c => c.Year)</td>
                    <td>
                        @Html.EditorFor(c => c.Year, new { htmlAttributes = new { @class = "form-control" } })
                    </td>
                </tr>
                <tr><td></td><td>@Html.ValidationMessageFor(c => c.Year)</td></tr>
                <tr class="row-separator"></tr>
                <tr>
                    <td>@Html.LabelFor(c => c.DeliveredOn)</td>
                    <td><input name="@nameof(Model.DeliveredOn)" id="@nameof(Model.DeliveredOn)" class="form-control" type="text" /></td>
                </tr>
                <tr><td></td><td>@Html.ValidationMessageFor(c => c.DeliveredOn)</td></tr>
                <tr class="row-separator"></tr>
            </tbody>
        </table>
    }
</div>

<script>
    $(document).ready(function() {
        $('table#addEditCarData input#@nameof(Model.DeliveredOn)').datepicker();
        $('table#addEditCarData input#@nameof(Model.DeliveredOn)').datepicker('option', 'dateFormat', 'yy-mm-dd');
        $('table#addEditCarData input#@nameof(Model.DeliveredOn)').datepicker('setDate', new Date(@Model.DeliveredOn.Year, @(Model.DeliveredOn.Month - 1), @Model.DeliveredOn.Day));
    });
</script>